version: '1'
services:
  server:
    container_name: 'ufirst-server'
    build:
      context: '.'
      dockerfile: Dockerfile
      args:
        PORT: 8080
    ports:
      - '8000:8080'
    volumes:
      - './src:/var/www/html'

